In [1]:
import numpy as np

In [105]:
x=[[1, 0, 0, 0, 1, 1, 0, 0, 1], [1, 0, 0, 0, 0, 1, 0, 0, 1], [0, 0, 1, 1, 0, 0, 1, 1, 1], [1, 1, 1, 1, 1, 0, 1, 1, 0], [1, 1, 1, 1, 1, 0, 1, 1, 0], [0, 0, 1, 1, 0, 0, 1, 1, 1], [1, 0, 0, 0, 0, 1, 0, 0, 1]]
y = np.hstack(x).reshape((len(x), len(x[0])))
y

array([[1, 0, 0, 0, 1, 1, 0, 0, 1],
       [1, 0, 0, 0, 0, 1, 0, 0, 1],
       [0, 0, 1, 1, 0, 0, 1, 1, 1],
       [1, 1, 1, 1, 1, 0, 1, 1, 0],
       [1, 1, 1, 1, 1, 0, 1, 1, 0],
       [0, 0, 1, 1, 0, 0, 1, 1, 1],
       [1, 0, 0, 0, 0, 1, 0, 0, 1]])

In [107]:
x = [[1, 0, 0, 0, 1, 1, 0, 0, 1], [1, 0, 0, 0, 0, 1, 0, 0, 1], [0, 0, 1, 1, 0, 0, 1, 1, 1], [1, 1, 1, 1, 1, 0, 1, 1, 0], [1, 1, 1, 1, 1, 0, 1, 1, 0], [0, 0, 1, 1, 0, 0, 1, 1, 1], [1, 0, 0, 0, 0, 1, 0, 0, 1]]
matrix = np.hstack(x).reshape((len(x), len(x[0])))
matrix

array([[1, 0, 0, 0, 1, 1, 0, 0, 1],
       [1, 0, 0, 0, 0, 1, 0, 0, 1],
       [0, 0, 1, 1, 0, 0, 1, 1, 1],
       [1, 1, 1, 1, 1, 0, 1, 1, 0],
       [1, 1, 1, 1, 1, 0, 1, 1, 0],
       [0, 0, 1, 1, 0, 0, 1, 1, 1],
       [1, 0, 0, 0, 0, 1, 0, 0, 1]])

In [48]:
mat = np.array([[0, 1, 1, 0],
               [1, 0, 0, 1],
               [1, 1, 1, 1],
               [0, 0, 0, 1]])
mat

array([[0, 1, 1, 0],
       [1, 0, 0, 1],
       [1, 1, 1, 1],
       [0, 0, 0, 1]])

In [104]:
def get_result(matrix):
    for i in range(matrix.shape[1] - 1):
        minimo = min(i, matrix.shape[1]-(i+2))
        submatrix = matrix[:, i-minimo:i+2+minimo]
        list_inverted = list(range(0, submatrix.shape[1]))
        inverse_submatrix = submatrix[:, list_inverted[::-1]]
        m = submatrix-inverse_submatrix
        all_zeros = not np.any(m)
        if all_zeros:
            # filas_izq = 
            return i+1, 0
    
    for i in range(matrix.shape[0] - 1):
        minimo = min(i, matrix.shape[0]-(i+2))
        submatrix = matrix[i-minimo:i+2+minimo, :]
        list_inverted = list(range(0, submatrix.shape[0]))
        inverse_submatrix = submatrix[list_inverted[::-1], :]
        m = submatrix-inverse_submatrix
        all_zeros = not np.any(m)
        if all_zeros:
            return i+1, 1

In [108]:
get_result(matrix)

(4, 1)